const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const SAVE='tomorrow-station-v1',gameSite=process.env.GAME_URL||'http://localhost:8080/tomorrow-station/';
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const errors=[];
 try{
  async function newPage(){const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.route('**/game.js',route=>route.fulfill({contentType:'text/javascript',body:fs.readFileSync('game.js','utf8').replace('requestAnimationFrame(frame);window.addEventListener','window.__check={get state(){return state},speak,advance,move,save,normaliseSave,transition:comfort.transition,get dialogue(){return conversation}};requestAnimationFrame(frame);window.addEventListener')}));await page.goto(gameSite);return page;}
  const page=await newPage(),get=()=>page.evaluate(()=>structuredClone(window.__check.state));
  await page.locator('#begin').click();
  await page.evaluate(()=>window.__check.speak('역무원 · 여울',['첫 문장','두 번째 문장','마지막 문장'],()=>{window.__check.state.met=true;}));
  assert(await page.locator('#previous').isDisabled());assert.equal((await get()).history.length,1);await page.locator('#next').click();assert.equal((await get()).history.length,2);await page.locator('#previous').click();assert.equal(await page.locator('#line').textContent(),'첫 문장');await page.locator('#next').click();assert.equal((await get()).history.length,2);assert.equal((await get()).met,false);await page.locator('#next').click();assert.equal((await get()).met,false);await page.locator('#next').click();assert((await get()).met);assert.equal((await get()).history.length,3);
  await page.locator('#journal-button').click();await page.locator('[data-journal-tab="history"]').click();assert.equal(await page.locator('.history-entry').count(),3);assert.equal(await page.locator('.history-entry p').first().textContent(),'마지막 문장');await page.locator('[data-journal-tab="map"]').click();assert.equal(await page.locator('.map-place[aria-current="location"]').first().textContent(),'대합실');await page.setViewportSize({width:320,height:568});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'screenshot-map-mobile.png'});const paused=await get();await page.keyboard.down('ArrowRight');await page.waitForTimeout(180);await page.keyboard.up('ArrowRight');assert.deepEqual(await get(),paused);await page.keyboard.press('Escape');
  await page.setViewportSize({width:1440,height:1000});await page.locator('#save-button').click();await page.locator('#save-slots button').first().click();const slot1=await page.evaluate(key=>localStorage.getItem(key),SAVE+'-slot-1');
  await page.evaluate(()=>{const t=window.__check,s=t.state;s.chapter=5;s.night5.met=true;s.night5.guestChoice='listen';s.night5.cup=true;s.night5.served=true;s.night5.route=['forest'];t.move(9,290,242);});
  await page.locator('#save-button').click();const downloadEvent=page.waitForEvent('download');await page.locator('#export-save').click();const download=await downloadEvent,payload=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(payload.format,'tomorrow-station');assert.equal(payload.version,1);assert.equal(payload.state.chapter,5);assert.deepEqual(payload.state.night5.route,['forest']);assert.equal(payload.state.history.length,3);assert(download.suggestedFilename().endsWith('.json'));
  await page.locator('#close-save-menu').click();await page.evaluate(()=>{window.__check.state.night5.route=['forest','connection'];window.__check.state.night5.ticket=true;window.__check.save();});await page.locator('#load-button').click();
  async function upload(target,content,name='journey.json'){await target.locator('#import-file').setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(content)});}
  const beforeImport=await get();await upload(page,JSON.stringify(payload));await page.locator('#import-preview').waitFor({state:'visible'});assert.deepEqual(await get(),beforeImport,'preview must not change progress');assert((await page.locator('#import-summary').textContent()).includes('환승 시간표'));
  await page.setViewportSize({width:320,height:568});await page.locator('#apply-import').scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'screenshot-import-mobile.png'});await page.locator('#apply-import').click();assert.deepEqual((await get()).night5.route,['forest']);assert.equal((await get()).night5.ticket,false);assert.equal(await page.evaluate(key=>localStorage.getItem(key),SAVE+'-slot-1'),slot1);
  await page.locator('#load-button').click();await page.locator('.save-slot').filter({hasText:'파일 가져오기 전 진행'}).getByRole('button').click();assert.deepEqual((await get()).night5.route,['forest','connection']);assert((await get()).night5.ticket);
  await page.locator('#load-button').click();const beforeInvalid=await get();
  for(const [input,error] of [['not json','올바른 JSON'],[JSON.stringify({format:'another-game',version:1,state:payload.state}),'이 게임에서 내보낸'],[JSON.stringify({...payload,state:{room:9,x:'NaN',y:200}}),'저장 내용이 올바르지'],[' '.repeat(512*1024+1),'512KB']]){await upload(page,input);await page.waitForFunction(error=>document.querySelector('#import-status').textContent.includes(error),error);assert.equal(await page.locator('#import-preview').isVisible(),false);assert.deepEqual(await get(),beforeInvalid);}
  await page.locator('#close-save-menu').click();await page.reload();await page.locator('#continue').click();assert((await get()).night5.ticket);assert.equal((await get()).history.length,3);
  // History stays bounded and imported text is displayed as text, not HTML.
  await page.evaluate(()=>{for(let i=0;i<85;i++)window.__check.speak('메모',['<img src=x onerror=alert(1)> '+i]);window.__check.advance();});assert.equal((await get()).history.length,80);await page.locator('#journal-button').click();await page.locator('[data-journal-tab="history"]').click();assert.equal(await page.locator('.history-entry').count(),80);assert.equal(await page.locator('#journal-content img').count(),0);await page.locator('#close-journal').click();
  await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>{window.__check.transition();return document.querySelector('#scene-stage').getAnimations().length;}),0);
  // Export/import into a clean browser from the title screen, without debug state changes.
  const other=await newPage();await other.locator('#load-button').click();assert(await other.locator('#export-save').isDisabled());await upload(other,JSON.stringify(payload));await other.locator('#import-preview').waitFor({state:'visible'});assert(await other.locator('#start').isVisible());await other.locator('#apply-import').click();assert.equal(await other.locator('#start').isVisible(),false);assert.deepEqual(await other.evaluate(()=>window.__check.state.night5.route),['forest']);assert((await other.locator('#location').textContent()).includes('당직실'));
  // A failed safety backup must leave the pending import unapplied; autosave failure is visible.
  await other.locator('#load-button').click();await upload(other,JSON.stringify({...payload,state:{...payload.state,chapter:1,room:0}}));await other.locator('#import-preview').waitFor({state:'visible'});await other.evaluate(()=>{window.__originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw new DOMException('Full','QuotaExceededError');};});await other.locator('#apply-import').click();assert((await other.locator('#import-status').textContent()).includes('복구용으로 보관하지 못했어요'));assert.equal(await other.evaluate(()=>window.__check.state.chapter),5);await other.locator('#close-save-menu').click();await other.evaluate(()=>window.__check.save());assert((await other.locator('#save-status').textContent()).includes('자동 저장 실패'));await other.evaluate(()=>{Storage.prototype.setItem=window.__originalSetItem;window.__check.save();});assert((await other.locator('#save-status').textContent()).includes('자동 저장됨'));
  assert.deepEqual(errors,[]);console.log('PASS: dialogue back/history without duplicate completion; bounded safe history; map and paused menus; real JSON download; cross-browser title-screen import; preview; backup restore; manual slots preserved; invalid/oversized file rejection; storage failure; reduced motion; 320px layout.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
